name: Report package build failure
description: Let us know about build failures in the project.
title: "[<port name>] build failure"
labels: ["category:bug"]
body:
  - type: input
    id: windows_version
    attributes:
      label: Windows version
      placeholder: "e.g. Windows 10 22H2, Windows 11 24H2"
    validations:
      required: true

  - type: input
    id: cmake_version
    attributes:
      label: CMake version
      placeholder: "e.g. 3.31.6-msvc6"
    validations:
      required: true

  - type: input
    id: msvc_version
    attributes:
      label: MSVC compiler version
      placeholder: "e.g. MSVC 19.44.35226.0"
    validations:
      required: true

  - type: input
    id: visualstudio_version
    attributes:
      label: Visual Studio/MSVC toolset version
      placeholder: "e.g. Visual Studio 2022 17.14, MSVC v143"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the behavior
      placeholder: "`./vcpkg install xxxx`"
      render: "Shell"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Failure logs
      description: The console output and all the logs mentioned in the output.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
