file(GLOB TEST_SOURCES CONFIGURE_DEPENDS "*.cpp")
if(TEST_SOURCES)
	add_executable(test_utils ${TEST_SOURCES})
	target_include_directories(test_utils PRIVATE ${CMAKE_SOURCE_DIR}/src)
	target_link_libraries(test_utils PRIVATE vccov_tools gtest gtest_main)
	add_test(NAME test_utils COMMAND test_utils)
else()
	message(STATUS "No utils tests found in ${CMAKE_CURRENT_SOURCE_DIR}")
endif()