if(VCCOV_ASAN)
  if(CMAKE_C_COMPILER_ID MATCHES "AppleClang|GNU|Clang")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
  elseif(MSVC)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /fsanitize=address")
  endif()
endif()

if(VCCOV_MSAN)
  if(CMAKE_C_COMPILER_ID MATCHES "AppleClang|GNU|Clang")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-omit-frame-pointer -fsanitize=memory")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fno-omit-frame-pointer -fsanitize=memory")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fno-omit-frame-pointer -fsanitize=memory")
  elseif(MSVC)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /fsanitize=memory")
  endif()
endif()

if(VCCOV_UBSAN)
  if(CMAKE_C_COMPILER_ID MATCHES "AppleClang|GNU|Clang")
        add_compile_options("-fsanitize=undefined" "-fno-sanitize-recover=undefined")
        if (NOT WIN32)
            add_link_options("-fsanitize=undefined")
        endif()
        if(MSVC)
            add_compile_options("/Oy-")
        else()
            add_compile_options("-fno-omit-frame-pointer")
        endif()
    endif()
endif()