name: cmake-build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        platform: [x64, Win32]
        configuration: [Release]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: install
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgTriplet: '${{ matrix.platform }}-windows'

      - name: Setup Visual Studio Environment Variables
        shell: pwsh
        run: |
          $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath
          echo "VSINSTALLDIR=$vsPath" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Configure CMake
        shell: pwsh
        run: |
          if ("${{ matrix.os }}" -eq "windows-2022") {
            $generator = "Visual Studio 17 2022"
          } else {
            $generator = "Visual Studio 16 2019"
          }
          cmake -G "$generator" `
            -A "${{ matrix.platform }}" `
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -S . `
            -B build/${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.configuration }}

      - name: Build
        shell: powershell
        run: >
          cmake --build build/${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.configuration }}
          --config ${{ matrix.configuration }}
